name: Call a reusable workflow and use its outputs

on:
  workflow_dispatch:

jobs:
  job1:
    uses: sparshbaurasi/hiup/.github/workflows/action.yaml@main
    secrets:
      CSSM_HW_FOODS_AZURE_CLIENT_ID: ${{ secrets.CSSM_HW_FOODS_AZURE_CLIENT_ID }}
      CSSM_HW_FOODS_AZURE_TENANT_ID: ${{ secrets.CSSM_HW_FOODS_AZURE_TENANT_ID }}
      CSSM_HW_FOODS_AZURE_SUBSCRIPTION_ID: ${{ secrets.CSSM_HW_FOODS_AZURE_SUBSCRIPTION_ID }}
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo ${{ needs.job1.outputs.secure_file }}
